site_name: Coleta Copiloto
theme:
  name: readthedocs
plugins:
- search 
- mkdocstrings:
    handlers:
      python:
        setup_commands:
          - import sys
          - sys.path.append("src")
    watch: 
      - src